"""add_group_role

Revision ID: 036b387ef907
Revises: c0367e62ae99
Create Date: 2023-10-13 15:01:38.183365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036b387ef907'
down_revision = 'c0367e62ae99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'role')
    # ### end Alembic commands ###
