"""add-url-mappings-table

Revision ID: 0475426eb625
Revises: 0daf32738b6d
Create Date: 2024-03-07 13:46:15.677506

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0475426eb625"
down_revision = "0daf32738b6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_mapping",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("client_url", sa.String(), nullable=True),
        sa.Column("worker_url", sa.String(), nullable=True),
        sa.Column("worker_ws_url", sa.String(), nullable=True),
        sa.Column(
            "date", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("url_mapping")
    # ### end Alembic commands ###
