"""add-uuid-primary-key-to-worker-status

Revision ID: 0daf32738b6d
Revises: 61120f014bcd
Create Date: 2024-02-28 18:19:56.688535

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0daf32738b6d"
down_revision = "61120f014bcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_status",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
    )
    op.drop_constraint("worker_status_pkey", "worker_status", type_="primary")
    op.create_primary_key("worker_status_pkey", "worker_status", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_status", "id")

    op.alter_column(
        "worker_status",
        "date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("worker_status", "id")
    # ### end Alembic commands ###
