"""added files to table

Revision ID: 0fe7b2d2a2a0
Revises: edc3fab2eac9
Create Date: 2023-10-30 10:37:38.191584

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fe7b2d2a2a0'
down_revision = 'edc3fab2eac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_fetcher')
    op.drop_table('functions')
    op.add_column('tables', sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'tables', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'file_id')
    op.create_table('functions',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='functions_page_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='functions_pkey')
    )
    op.create_table('data_fetcher',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='data_fetcher_page_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='data_fetcher_pkey')
    )
    # ### end Alembic commands ###
