"""added after to component

Revision ID: 19d1218f9bca
Revises: 7494c6efce60
Create Date: 2023-09-20 12:57:24.366325

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19d1218f9bca'
down_revision = '7494c6efce60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('after', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'components', 'components', ['after'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.drop_column('components', 'after')
    # ### end Alembic commands ###
