"""removed type from table

Revision ID: 3462f1e7ab30
Revises: 0fe7b2d2a2a0
Create Date: 2023-10-31 17:48:54.232297

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3462f1e7ab30'
down_revision = '0fe7b2d2a2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
