"""added table meta to sqls

Revision ID: 46c30403201a
Revises: 4799d66f486d
Create Date: 2023-08-17 11:19:31.840809

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46c30403201a'
down_revision = '4799d66f486d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sqls', sa.Column('table_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sqls', 'table_meta')
    # ### end Alembic commands ###
