"""added name to columns

Revision ID: 4787902286a7
Revises: fd64fa8fec52
Create Date: 2023-09-07 16:12:25.797691

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4787902286a7'
down_revision = 'fd64fa8fec52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columns', 'name')
    # ### end Alembic commands ###
