"""added dataclass to sqls and components tables

Revision ID: 4799d66f486d
Revises: 652061712d6d
Create Date: 2023-08-15 12:56:50.772576

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4799d66f486d'
down_revision = '652061712d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('dataclass', sa.String(), nullable=True))
    op.add_column('sqls', sa.Column('dataclass', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sqls', 'dataclass')
    op.drop_column('components', 'dataclass')
    # ### end Alembic commands ###
