"""added test code to functions table

Revision ID: 49417774ae53
Revises: 4787902286a7
Create Date: 2023-09-13 12:11:54.636695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '49417774ae53'
down_revision = '4787902286a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('test_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'test_code')
    # ### end Alembic commands ###
