"""add_policy_table

Revision ID: 50fa4f4940a0
Revises: 15235877d26e
Create Date: 2023-09-26 17:11:10.607494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50fa4f4940a0'
down_revision = '15235877d26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ptype', sa.String(), nullable=False),
    sa.Column('v0', sa.String(), nullable=True),
    sa.Column('v1', sa.String(), nullable=True),
    sa.Column('v2', sa.String(), nullable=True),
    sa.Column('v3', sa.String(), nullable=True),
    sa.Column('v4', sa.String(), nullable=True),
    sa.Column('v5', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy')
    # ### end Alembic commands ###
