"""add_confirmation_token_to_user

Revision ID: 52ce898b548d
Revises: 99233acaf072
Create Date: 2023-11-27 15:08:04.017033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "52ce898b548d"
down_revision = "99233acaf072"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("confirmation_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "confirmation_token")
    # ### end Alembic commands ###
