"""add_policy_unique_constaint

Revision ID: 545f34bdb629
Revises: f027146ce410
Create Date: 2023-10-23 17:02:10.376785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545f34bdb629'
down_revision = 'f027146ce410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_policy_constraint', 'policy', ['ptype', 'v0', 'v1', 'v2', 'v3', 'v4', 'v5', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_policy_constraint', 'policy', type_='unique')
    # ### end Alembic commands ###
