"""add-trial-fields-to-workspace

Revision ID: 5f994e35278e
Revises: f6a13e02f583
Create Date: 2024-02-02 15:50:14.818745

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f994e35278e"
down_revision = "f6a13e02f583"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("in_trial", sa.Boolean(), nullable=True))
    op.add_column(
        "workspace",
        sa.Column(
            "trial_end_date",
            sa.DateTime(),
            server_default=sa.text("(NOW() + INTERVAL '14 days')"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "trial_end_date")
    op.drop_column("workspace", "in_trial")
    # ### end Alembic commands ###
