"""Added user onboarded flag
Revision ID: 61120f014bcd
Revises: d94c3964da68
Create Date: 2024-02-26 16:09:33.376312
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61120f014bcd"
down_revision = "d94c3964da68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("onboarded", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "onboarded")
    # ### end Alembic commands ###
