"""add-type-to-function-table

Revision ID: 652061712d6d
Revises: 6fb25e199a22
Create Date: 2023-08-10 12:24:52.719654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652061712d6d'
down_revision = '6fb25e199a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'type')
    # ### end Alembic commands ###
