"""added source_id and type to table

Revision ID: 7494c6efce60
Revises: 49417774ae53
Create Date: 2023-09-19 20:15:46.768560

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7494c6efce60'
down_revision = '49417774ae53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinned_filters', sa.Column('table_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('pinned_filters_sql_id_fkey', 'pinned_filters', type_='foreignkey')
    op.create_foreign_key(None, 'pinned_filters', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pinned_filters', 'sql_id')
    op.add_column('tables', sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('tables', sa.Column('type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tables', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'type')
    op.drop_column('tables', 'source_id')
    op.add_column('pinned_filters', sa.Column('sql_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pinned_filters', type_='foreignkey')
    op.create_foreign_key('pinned_filters_sql_id_fkey', 'pinned_filters', 'tables', ['sql_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pinned_filters', 'table_id')
    # ### end Alembic commands ###
