"""removed sources

Revision ID: 8173146060eb
Revises: 545f34bdb629
Create Date: 2023-10-26 12:41:29.337855

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8173146060eb'
down_revision = '545f34bdb629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tables_source_id_fkey', 'tables', type_='foreignkey')
    op.drop_column('tables', 'source_id')
    op.drop_table('source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tables_source_id_fkey', 'tables', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_table('source',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creds', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name='source_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='source_pkey')
    )
    # ### end Alembic commands ###
