"""removed name from column table

Revision ID: 89b4061e920e
Revises: 3eee2beb14a8
Create Date: 2023-09-05 19:32:15.941075

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '89b4061e920e'
down_revision = '3eee2beb14a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columns', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
