"""add-new-fields-to-app-table

Revision ID: 900dcddf7404
Revises: dbc019af267c
Create Date: 2024-01-31 14:53:20.541623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "900dcddf7404"
down_revision = "dbc019af267c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("label", sa.String(), nullable=True))
    op.add_column("app", sa.Column("description", sa.String(), nullable=True))
    op.alter_column("app", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("app", "is_draft")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app", sa.Column("is_draft", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.alter_column("app", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("app", "description")
    op.drop_column("app", "label")
    # ### end Alembic commands ###
