"""add_worker_url_to_workspace

Revision ID: 99233acaf072
Revises: b557e11e628e
Create Date: 2023-11-23 15:41:23.955009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "99233acaf072"
down_revision = "b557e11e628e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("worker_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "worker_url")
    # ### end Alembic commands ###
