"""adding worker_status table

Revision ID: a3262eb43cfc
Revises: e2b99cb5cc26
Create Date: 2023-12-04 14:07:27.698994

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3262eb43cfc'
down_revision = 'e2b99cb5cc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_status',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token', 'date')
    )
    op.drop_table('pinned_filters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_filters',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('sorts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('table_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='pinned_filters_table_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pinned_filters_pkey')
    )
    op.drop_table('worker_status')
    # ### end Alembic commands ###
