"""add_name_and_region_fields_to_token_table

Revision ID: a4308d27bbec
Revises: 2b67d3d650d1
Create Date: 2023-11-16 14:32:19.406948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4308d27bbec'
down_revision = '2b67d3d650d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('name', sa.String(), nullable=True))
    op.add_column('token', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'region')
    op.drop_column('token', 'name')
    # ### end Alembic commands ###
