"""added dependent_on to table

Revision ID: a7a3fb212104
Revises: 15235877d26e
Create Date: 2023-09-26 19:42:56.824844

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7a3fb212104'
down_revision = '15235877d26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('depends_on', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'depends_on')
    # ### end Alembic commands ###
