"""added column table, renamed action to widget

Revision ID: ba98031d2fb8
Revises: 1a8a379b676e
Create Date: 2023-08-31 12:05:11.635601

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba98031d2fb8'
down_revision = '1a8a379b676e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('page_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('columns',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('property', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sql_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sql_id'], ['sqls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('components', sa.Column('widget_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('components_action_id_fkey', 'components', type_='foreignkey')
    op.create_foreign_key(None, 'components', 'widget', ['widget_id'], ['id'], ondelete='CASCADE')
    op.drop_column('components', 'action_id')
    op.add_column('functions', sa.Column('page_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('functions_action_id_fkey', 'functions', type_='foreignkey')
    op.create_foreign_key(None, 'functions', 'page', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_column('functions', 'action_id')
    op.add_column('sqls', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('sqls', 'table_meta')
    op.drop_table('action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sqls', sa.Column('table_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('sqls', 'name')
    op.add_column('functions', sa.Column('action_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'functions', type_='foreignkey')
    op.create_foreign_key('functions_action_id_fkey', 'functions', 'action', ['action_id'], ['id'], ondelete='CASCADE')
    op.drop_column('functions', 'page_id')
    op.add_column('components', sa.Column('action_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.create_foreign_key('components_action_id_fkey', 'components', 'action', ['action_id'], ['id'], ondelete='CASCADE')
    op.drop_column('components', 'widget_id')
    op.create_table('action',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dataclass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='action_page_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='action_pkey')
    )
    op.drop_table('columns')
    op.drop_table('widget')
    # ### end Alembic commands ###
