"""added token and ports for api and lsp to workspace

Revision ID: c0367e62ae99
Revises: 80b3b82a6dc3
Create Date: 2023-10-13 11:39:27.937068

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0367e62ae99'
down_revision = '80b3b82a6dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('api_token', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('api_port', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('lsp_port', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'lsp_port')
    op.drop_column('workspace', 'api_port')
    op.drop_column('workspace', 'api_token')
    # ### end Alembic commands ###
