"""add_workspace_id_to_policy_table

Revision ID: d567d8cca21b
Revises: 31ee615a2779
Create Date: 2023-10-05 16:35:12.311057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d567d8cca21b"
down_revision = "31ee615a2779"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("policy", sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "policy", "workspace", ["workspace_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "policy", type_="foreignkey")
    op.drop_column("policy", "workspace_id")

    # ### end Alembic commands ###
