"""Added social_login column

Revision ID: d94c3964da68
Revises: dfe66f63ddd8
Create Date: 2024-02-20 17:37:35.416148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94c3964da68'
down_revision = 'dfe66f63ddd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_login', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_login')
    # ### end Alembic commands ###
