"""add_reset_token_table

Revision ID: e2b99cb5cc26
Revises: 52ce898b548d
Create Date: 2023-11-29 12:08:39.147826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e2b99cb5cc26"
down_revision = "52ce898b548d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reset_token",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("hashed_token", sa.String(), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("expiration_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reset_token")
    # ### end Alembic commands ###
