"""added property field to tables

Revision ID: ed949348c91b
Revises: ba98031d2fb8
Create Date: 2023-08-31 17:04:13.660259

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed949348c91b'
down_revision = 'ba98031d2fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('property', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sqls', sa.Column('property', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('widget', sa.Column('property', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget', 'property')
    op.drop_column('sqls', 'property')
    op.drop_column('components', 'property')
    # ### end Alembic commands ###
