"""add_is_draft_to_app_table

Revision ID: edc3fab2eac9
Revises: 6851ffc905e4
Create Date: 2023-10-27 18:22:15.724453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc3fab2eac9'
down_revision = '6851ffc905e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('is_draft', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'is_draft')
    # ### end Alembic commands ###
