"""add-new-fields-to-page-table

Revision ID: f6a13e02f583
Revises: 900dcddf7404
Create Date: 2024-01-31 15:19:00.833939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f6a13e02f583"
down_revision = "900dcddf7404"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("label", sa.String(), nullable=True))
    op.add_column("page", sa.Column("description", sa.String(), nullable=True))
    op.alter_column("page", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("page", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("page", "description")
    op.drop_column("page", "label")

    # ### end Alembic commands ###
