"""change worker_ws_url_to_lsp_url

Revision ID: fceb864a9edb
Revises: 0475426eb625
Create Date: 2024-03-07 16:46:03.722212

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fceb864a9edb"
down_revision = "0475426eb625"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("url_mapping", sa.Column("lsp_url", sa.String(), nullable=True))
    op.drop_column("url_mapping", "worker_ws_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "url_mapping",
        sa.Column("worker_ws_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("url_mapping", "lsp_url")
    # ### end Alembic commands ###
