"""added name to functions

Revision ID: fd64fa8fec52
Revises: 89b4061e920e
Create Date: 2023-09-07 11:41:30.120709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fd64fa8fec52'
down_revision = '89b4061e920e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'name')
    # ### end Alembic commands ###
