name: Build client docker image

on:
  push:
    branches:
      - main
    paths:
      - client/**
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-client-docker-image:
    name: Build client docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare image tags
        id: image-tags
        run: |
          base=dropbase/client

          ## Set git tag as image tag
          ##
          if [[ '${{ github.ref }}' == *"refs/tags/"* ]]; then
            github_tag="${GITHUB_REF#refs/*/}"

            SEMVER_REGEX="^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"
            if [[ "$github_tag" =~ $SEMVER_REGEX ]]; then
              github_tag=$(echo "${github_tag}" | sed 's/^v//')
            fi

            container_images=$(cat <<END_HEREDOC
          ${base}:${github_tag}
          END_HEREDOC
          )
          
          ## Set 'latest' image tag if 'main' or 'master'
          ## branch is pushed
          ##
          elif [[ '${{ github.ref }}' == 'refs/heads/master' || '${{ github.ref }}' == 'refs/heads/main' ]]; then
            container_images=$(cat <<END_HEREDOC
          ${base}:latest
          END_HEREDOC
            )
          fi

          ## Print tags for debugging purpose
          ##
          echo "[INFO] container_images: ${container_images}"
          
          ## Set container_images output
          ##
          echo "container_images<<EOF" >> $GITHUB_OUTPUT
          echo "$container_images" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: client
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.image-tags.outputs.container_images }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
