name: Test building client

on:
  pull_request:
    paths:
      - client/**
    branches:
      - main
      - dev

env:
  CLIENT_URL: "https://dev.dropbase.io"
  VITE_API_ENDPOINT: "https://api.dev.dropbase.io/"
  VITE_PYTHON_LSP_SERVER: "wss://api.dev.dropbase.io"
  VITE_WORKER_API_ENDPOINT: "https://api.dev.dropbase.io"

jobs:
  test-build:
    name: Test building client
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd client && yarn install

      - name: Build
        run: cd client && yarn run build
